### ISSUE TITLE
Unhandled Promise Rejection: AbortError: Fetch is aborted

### ISSUE THREAD

**Issue by andreobrown** [mrhead/stimulus-search#3]
I've implemented the search feature in my Rails 5.2 application, and it works. Thanks for this example!

However, I'm getting the following error in the browser javascript console:

`Unhandled Promise Rejection: AbortError: Fetch is aborted`

Any idea what's causing this?

**Comment by mrhead** [comment]
That error happens when a fetch request is aborted: https://github.com/mrhead/stimulus-search/blob/master/app/javascript/controllers/search_controller.js#L50

It's harmless and you can read about it more here: https://developers.google.com/web/updates/2017/09/abortable-fetch -> Reacting to an aborted fetch
